services:
  app:
    build: .
    container_name: entregableU3
    ports:
      - "3000:3000"
    depends_on:
      - redis_stack
      - neo4j
    environment:
      - NEO4J_URL=neo4j://neo01:7687
    volumes:
      - ./Regs:/app
    networks:
      - backend
    command: npm start
  
  redis_stack:
    image: redis/redis-stack
    container_name: redisStack
    ports:
      - "6379:6379"
      - "8001:8001"
    depends_on:
      - neo4j
    networks:
      - backend

  neo4j:
    image: neo4j
    container_name: neo01
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none
    networks:
      - backend

networks:
  backend:
    driver: bridge